"""
Verdant – Dummy Data Generator
Generates JSON files for all MongoDB collections with realistic,
cross-referenced ObjectIds. Run this once, then use seed_db.py to upload.

Usage:
    cd backend
    py dummydata/generate_dummy_data.py
"""

import json
import hashlib
import random
import os
from datetime import datetime, timezone, timedelta
from bson import ObjectId

OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))

random.seed(42)

# ── Helper ──────────────────────────────────────────────────
def oid():
    return str(ObjectId())

def ts(days_ago=0, hours_ago=0):
    dt = datetime.now(timezone.utc) - timedelta(days=days_ago, hours=hours_ago)
    return dt.isoformat()

def sha256(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()

def write_json(filename, data):
    path = os.path.join(OUTPUT_DIR, filename)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, default=str)
    print(f"  ✓ {filename}: {len(data)} documents")

# ── 1. Users ────────────────────────────────────────────────
# Password for ALL dummy users: "Verdant@123"
# The actual hash is generated by seed_db.py using argon2
DUMMY_PASSWORD = "Verdant@123"

admin_ids = [oid() for _ in range(2)]
producer_user_ids = [oid() for _ in range(10)]
consumer_ids = [oid() for _ in range(20)]

all_user_ids = admin_ids + producer_user_ids + consumer_ids

admin_names = ["Admin Sharma", "Super Admin Patel"]
admin_emails = ["admin@verdant.io", "superadmin@verdant.io"]

producer_names = [
    "Rajesh Kumar", "Priya Mehta", "Vikram Singh", "Ananya Reddy",
    "Suresh Joshi", "Kavita Nair", "Arjun Desai", "Meera Iyer",
    "Deepak Gupta", "Sanya Kapoor"
]
producer_emails = [f"producer{i+1}@verdant.io" for i in range(10)]

consumer_names = [
    "Amit Verma", "Sneha Agarwal", "Rohit Bansal", "Pooja Chauhan",
    "Nikhil Deshpande", "Ritu Fernandez", "Gaurav Hegde", "Isha Jain",
    "Karan Kulkarni", "Lakshmi Menon", "Manoj Naik", "Nandini Oza",
    "Omkar Patil", "Pallavi Qureshi", "Rahul Saxena", "Tanya Thakur",
    "Uday Vyas", "Vandana Wagh", "Waseem Xavier", "Yamini Zaveri"
]
consumer_emails = [f"consumer{i+1}@verdant.io" for i in range(20)]

users = []
for i, uid in enumerate(admin_ids):
    users.append({
        "_id": uid,
        "email": admin_emails[i],
        "hashed_password": "__PLACEHOLDER__",
        "full_name": admin_names[i],
        "role": "admin",
        "is_active": True,
        "refresh_token": None,
        "created_at": ts(days_ago=180),
        "updated_at": ts(days_ago=1),
    })

for i, uid in enumerate(producer_user_ids):
    users.append({
        "_id": uid,
        "email": producer_emails[i],
        "hashed_password": "__PLACEHOLDER__",
        "full_name": producer_names[i],
        "role": "producer",
        "is_active": True,
        "refresh_token": None,
        "created_at": ts(days_ago=random.randint(60, 160)),
        "updated_at": ts(days_ago=random.randint(0, 10)),
    })

for i, uid in enumerate(consumer_ids):
    users.append({
        "_id": uid,
        "email": consumer_emails[i],
        "hashed_password": "__PLACEHOLDER__",
        "full_name": consumer_names[i],
        "role": "consumer",
        "is_active": True,
        "refresh_token": None,
        "created_at": ts(days_ago=random.randint(30, 150)),
        "updated_at": ts(days_ago=random.randint(0, 15)),
    })

# ── 2. Producers ────────────────────────────────────────────
producer_ids = [oid() for _ in range(10)]

company_names = [
    "SolarFarm Alpha", "WindTech Pune", "HydroFlow Kerala",
    "GreenWind Tamil Nadu", "MicroSolar Goa", "SunPower Rajasthan",
    "Windharvest Gujarat", "BioEnergy Maharashtra", "GeoTherm Karnataka",
    "AquaPower Meghalaya"
]

descriptions = [
    "Largest solar installation in western Maharashtra with 50MW capacity.",
    "Offshore wind farm providing consistent energy to Pune metro.",
    "Run-of-river hydro project in Idukki district, Kerala.",
    "Onshore wind farm in Tirunelveli with 120 turbines.",
    "Distributed rooftop solar across 500 homes in South Goa.",
    "Utility-scale solar park in Jaisalmer, Rajasthan.",
    "Wind energy cluster in Kutch region, Gujarat.",
    "Biomass gasification plant using agricultural waste in Kolhapur.",
    "Experimental geothermal pilot in Raichur, Karnataka.",
    "Small hydro project on Umiam river, Meghalaya.",
]

locations = [
    "Pune, Maharashtra", "Pune, Maharashtra", "Idukki, Kerala",
    "Tirunelveli, Tamil Nadu", "South Goa, Goa", "Jaisalmer, Rajasthan",
    "Kutch, Gujarat", "Kolhapur, Maharashtra", "Raichur, Karnataka",
    "Shillong, Meghalaya"
]

energy_source_lists = [
    ["solar"], ["wind"], ["hydro"],
    ["wind"], ["solar"], ["solar"],
    ["wind"], ["biomass"], ["geothermal"],
    ["hydro"]
]

capacities = [50000, 32000, 25000, 48000, 5000, 80000, 42000, 12000, 3000, 8000]

producers = []
for i, pid in enumerate(producer_ids):
    status = "verified" if i < 8 else "pending"
    producers.append({
        "_id": pid,
        "owner_id": producer_user_ids[i],
        "company_name": company_names[i],
        "description": descriptions[i],
        "energy_sources": energy_source_lists[i],
        "capacity_kw": capacities[i],
        "location": locations[i],
        "status": status,
        "verified_by": admin_ids[0] if status == "verified" else None,
        "created_at": ts(days_ago=random.randint(50, 150)),
        "updated_at": ts(days_ago=random.randint(0, 10)),
    })

# ── 3. Energy Listings ──────────────────────────────────────
listing_ids = [oid() for _ in range(40)]

listing_titles = [
    "Premium Solar Bundle — 500kWh", "Wind Energy Pack — 300kWh",
    "Hydro Clean Energy — 200kWh", "Solar Residential — 100kWh",
    "Wind Farm Surplus — 800kWh", "Micro Solar — 50kWh",
    "Green Hydro — 400kWh", "Biomass Baseload — 600kWh",
    "Geothermal Steady — 150kWh", "River Hydro — 250kWh",
]

listings = []
for i, lid in enumerate(listing_ids):
    pidx = i % 10
    src = energy_source_lists[pidx][0]
    qty = random.choice([50, 100, 150, 200, 300, 400, 500, 600, 800, 1000])
    price = round(random.uniform(3.5, 9.5), 2)
    days_ago = random.randint(1, 90)

    if i < 25:
        status = "active"
    elif i < 32:
        status = "sold"
    elif i < 36:
        status = "expired"
    else:
        status = "cancelled"

    listings.append({
        "_id": lid,
        "producer_id": producer_ids[pidx],
        "owner_id": producer_user_ids[pidx],
        "title": f"{listing_titles[pidx % 10]} #{i+1}",
        "description": f"High-quality {src} energy from {company_names[pidx]}. Certified green.",
        "energy_source": src,
        "quantity_kwh": qty,
        "price_per_kwh": price,
        "min_purchase_kwh": max(1.0, qty * 0.05),
        "status": status,
        "available_from": ts(days_ago=days_ago),
        "available_until": ts(days_ago=days_ago - 60) if status == "expired" else None,
        "created_at": ts(days_ago=days_ago),
        "updated_at": ts(days_ago=max(0, days_ago - random.randint(0, 5))),
    })

# ── 4. Contracts ─────────────────────────────────────────────
contract_ids = [oid() for _ in range(50)]

contracts = []
for i, cid in enumerate(contract_ids):
    buyer = random.choice(consumer_ids)
    pidx = i % 10
    listing = listings[i % len(listings)]
    vol = random.choice([25, 50, 100, 150, 200, 300, 500])
    ppk = round(random.uniform(4.0, 9.0), 2)
    total = round(vol * ppk, 2)
    days_ago = random.randint(1, 120)
    ctype = random.choice(["spot", "scheduled"])

    if i < 30:
        status = "settled"
        sig_b = True
        sig_p = True
        settled_at = ts(days_ago=max(0, days_ago - 2))
    elif i < 40:
        status = "active"
        sig_b = True
        sig_p = random.choice([True, False])
        settled_at = None
    elif i < 45:
        status = "pending"
        sig_b = False
        sig_p = False
        settled_at = None
    else:
        status = "disputed"
        sig_b = True
        sig_p = True
        settled_at = None

    contracts.append({
        "_id": cid,
        "buyer_id": buyer,
        "producer_id": producer_ids[pidx],
        "listing_id": listing["_id"],
        "volume_kwh": vol,
        "price_per_kwh": ppk,
        "total_amount": total,
        "contract_type": ctype,
        "status": status,
        "contract_hash": sha256(f"{cid}-{buyer}-{vol}") if status in ("settled", "active") else None,
        "signature_buyer": sig_b,
        "signature_producer": sig_p,
        "settled_at": settled_at,
        "created_at": ts(days_ago=days_ago),
        "updated_at": ts(days_ago=max(0, days_ago - 1)),
    })

# ── 5. Certificates ─────────────────────────────────────────
cert_ids = [oid() for _ in range(30)]
settled_contracts = [c for c in contracts if c["status"] == "settled"]

certificates = []
for i, certid in enumerate(cert_ids):
    sc = settled_contracts[i % len(settled_contracts)]
    pidx = next((j for j, p in enumerate(producer_ids) if p == sc["producer_id"]), 0)
    src = energy_source_lists[pidx][0]
    days_ago = random.randint(1, 80)

    certificates.append({
        "_id": certid,
        "contract_id": sc["_id"],
        "producer_id": sc["producer_id"],
        "buyer_id": sc["buyer_id"],
        "energy_source": src,
        "energy_amount_kwh": sc["volume_kwh"],
        "certificate_hash": sha256(f"CERT-{certid}-{sc['_id']}"),
        "issued_at": ts(days_ago=days_ago),
        "expires_at": ts(days_ago=days_ago - 365),
        "valid": True,
        "created_at": ts(days_ago=days_ago),
        "updated_at": ts(days_ago=max(0, days_ago - 1)),
    })

# ── 6. Payments ──────────────────────────────────────────────
payment_ids = [oid() for _ in range(45)]

payments = []
for i, payid in enumerate(payment_ids):
    c = contracts[i % len(contracts)]
    days_ago = random.randint(1, 100)

    if c["status"] == "settled":
        pstatus = "completed"
        settled_at = ts(days_ago=max(0, days_ago - 1))
    elif c["status"] == "pending":
        pstatus = "pending"
        settled_at = None
    elif c["status"] == "disputed":
        pstatus = random.choice(["completed", "pending"])
        settled_at = ts(days_ago=max(0, days_ago - 1)) if pstatus == "completed" else None
    else:
        pstatus = random.choice(["completed", "pending"])
        settled_at = ts(days_ago=max(0, days_ago - 1)) if pstatus == "completed" else None

    payments.append({
        "_id": payid,
        "contract_id": c["_id"],
        "buyer_id": c["buyer_id"],
        "amount_eur": c["total_amount"],
        "status": pstatus,
        "escrow_lock": pstatus == "pending",
        "transaction_ref": f"TXN-{payid[:8].upper()}" if pstatus == "completed" else None,
        "settled_at": settled_at,
        "created_at": ts(days_ago=days_ago),
        "updated_at": ts(days_ago=max(0, days_ago - 1)),
    })

# ── 7. Disputes ──────────────────────────────────────────────
disputed_contracts = [c for c in contracts if c["status"] == "disputed"]
dispute_ids = [oid() for _ in range(8)]

dispute_descriptions = [
    "Energy delivery was 40% below contracted volume. Smart meter readings confirm deficit.",
    "Payment was deducted but no energy credit received after 72 hours.",
    "Certificate hash mismatch — possible tampering detected during verification.",
    "Producer failed to deliver scheduled energy on 3 consecutive days.",
    "Pricing discrepancy: was charged ₹8.2/kWh instead of agreed ₹5.5/kWh.",
    "Smart meter shows anomalous readings during the delivery window.",
    "Duplicate charge for the same contract — need refund for second payment.",
    "Energy source mismatch: contract specifies solar but meter data suggests grid power.",
]

disputes = []
for i, did in enumerate(dispute_ids):
    if i < len(disputed_contracts):
        cid = disputed_contracts[i]["_id"]
        raiser = disputed_contracts[i]["buyer_id"]
    else:
        c = random.choice(settled_contracts)
        cid = c["_id"]
        raiser = c["buyer_id"]

    days_ago = random.randint(1, 60)
    statuses = ["open", "reviewing", "resolved"]
    dstatus = statuses[i % 3]

    evidence = []
    if i % 2 == 0:
        evidence.append({
            "file_url": f"https://storage.verdant.io/evidence/dispute-{did[:8]}.pdf",
            "description": "Smart meter log export for the disputed period.",
            "uploaded_at": ts(days_ago=max(0, days_ago - 2)),
        })

    audit = [
        {"timestamp": ts(days_ago=days_ago), "actor": str(raiser), "action": "Dispute raised"},
    ]
    if dstatus in ("reviewing", "resolved"):
        audit.append({"timestamp": ts(days_ago=max(0, days_ago - 3)), "actor": admin_ids[0], "action": "Assigned for review"})
    if dstatus == "resolved":
        audit.append({"timestamp": ts(days_ago=max(0, days_ago - 5)), "actor": admin_ids[0], "action": "Dispute resolved"})

    disputes.append({
        "_id": did,
        "contract_id": cid,
        "raised_by": raiser,
        "status": dstatus,
        "description": dispute_descriptions[i],
        "resolution_note": "Refund issued and producer warned." if dstatus == "resolved" else None,
        "evidence": evidence,
        "audit_log": audit,
        "created_at": ts(days_ago=days_ago),
        "updated_at": ts(days_ago=max(0, days_ago - 2)),
    })

# ── 8. Smart Meter Readings ─────────────────────────────────
device_ids = [f"SM-{company_names[i].replace(' ', '-').upper()[:10]}-{random.randint(1000,9999)}" for i in range(10)]

meter_readings = []
for pidx in range(10):
    device = device_ids[pidx]
    base_kwh = random.uniform(100, 1000)
    # Generate 15 readings per producer (every ~6 hours over ~4 days)
    for j in range(15):
        hours_ago = j * 6
        reading = round(base_kwh + j * random.uniform(5, 30), 2)
        prev_reading = round(base_kwh + (j - 1) * random.uniform(5, 30), 2) if j > 0 else None
        is_anomaly = random.random() < 0.08  # 8% anomaly rate

        meter_readings.append({
            "_id": oid(),
            "device_id": device,
            "producer_id": producer_ids[pidx],
            "reading_kwh": reading,
            "previous_reading_kwh": prev_reading,
            "status": "anomaly" if is_anomaly else "synced",
            "anomaly_reason": "Sudden spike detected: reading jumped >50% in one interval" if is_anomaly else None,
            "timestamp": ts(hours_ago=hours_ago),
            "created_at": ts(hours_ago=hours_ago),
            "updated_at": ts(hours_ago=max(0, hours_ago - 1)),
        })

# ── Write all JSON files ────────────────────────────────────
print("Generating dummy data files...\n")
write_json("users.json", users)
write_json("producers.json", producers)
write_json("energy_listings.json", listings)
write_json("contracts.json", contracts)
write_json("certificates.json", certificates)
write_json("payments.json", payments)
write_json("disputes.json", disputes)
write_json("smart_meter_readings.json", meter_readings)

print(f"\n✅ All files generated in {OUTPUT_DIR}")
print(f"   Total documents: {len(users) + len(producers) + len(listings) + len(contracts) + len(certificates) + len(payments) + len(disputes) + len(meter_readings)}")
print(f"\n   Default password for all users: {DUMMY_PASSWORD}")
print("   Run 'py dummydata/seed_db.py' to upload to MongoDB.")
